### ISSUE TITLE
how to pull image using ocic?

### ISSUE THREAD

**Issue by haiyanmeng** [mrunalp/ocid#28]
I tried to pull a docker image with ocic, and got the following error:

```
sudo ./ocic pullimage docker.io/busybox
2016/08/03 15:11:18 pulling image failed: rpc error: code = 2 desc = "Invalid image name \"docker.io/busybox\", expected colon-separated transport:reference"
```

Clearly I missed something here.

**Comment by haiyanmeng** [comment]
@runcom , I need your help. Thanks.

**Comment by runcom** [comment]
./ocid pullimage busybox:latest (w/o sudo and w/o docker.io prefix)

**Comment by haiyanmeng** [comment]
@runcom , I tried these three commands with the latest upstream master branch, and failed:

```
[hmeng@localhost ocid]$ sudo ./ocic pullimage busybox:latest
2016/08/03 16:22:42 pulling image failed: rpc error: code = 2 desc = "Invalid image name \"busybox:latest\", unknown transport \"busybox\""

[hmeng@localhost ocid]$ sudo ./ocic pullimage docker.io:busybox:latest
2016/08/03 16:23:32 pulling image failed: rpc error: code = 2 desc = "Invalid image name \"docker.io:busybox:latest\", unknown transport \"docker.io\""

[hmeng@localhost ocid]$ sudo ./ocic pullimage docker.io/busybox:latest
2016/08/03 16:23:37 pulling image failed: rpc error: code = 2 desc = "Invalid image name \"docker.io/busybox:latest\", unknown transport \"docker.io/busybox\""
```

**Comment by runcom** [comment]
Alright, I'm probably missing something. I'm AFK right now. I'll try as soon as I get home. Try this in the mean time:

./ocic pullimage docker://busybox:latest

**Comment by haiyanmeng** [comment]
@runcom , I tried the new command you suggested, and the format is correct. 
But it still has a tiny problem you may want to look into:

```
[hmeng@localhost ocid]$ sudo ./ocic pullimage docker://busybox:latest
2016/08/03 16:38:23 pulling image failed: rpc error: code = 5 desc = "mkdir /var/lib/ocid/images///busybox:latest: no such file or directory"
```

**Comment by runcom** [comment]
Ah great, thanks for looking, something might have changed since my original PR then. I'll look into this tomorrow first thing.

**Comment by runcom** [comment]
@hmeng-19 found it:

``` sh
$ sudo mkdir -p /var/lib/ocid/images
```

that dir tree is missing, we should ensure `ocid` checks for that directory and create it if it's not already there before pulling

I left this as a TODO here https://github.com/mrunalp/ocid/pull/12#issue-166529718 (in the code block as a comment)

**Comment by haiyanmeng** [comment]
@runcom , cool. Thanks for looking into this.

Just a quick question, is there any special reason we are currently using `docker`, instead of `docker.io`, as the image registry?

**Comment by runcom** [comment]
> Just a quick question, is there any special reason we are currently using docker, instead of docker.io, as the image registry?

docker just defines the _protocol_ meaning try to pull from _a_ docker registry while _docker.io_ is the Docker Hub

**Comment by haiyanmeng** [comment]
Got it. Thanks.
