### ISSUE TITLE
Run the container as User

### ISSUE THREAD

**Issue by runcom** [mrunalp/ocid#5]
Reading the protobuf API I cannot seem to find out an User property used to run the container as User = "user". Is this intentional? why is there no way to run the contianer as a user other than root?

In k8s, I found `PodSecurityContext` which has a property to run the container as a user other than root, wanted to understand if the CRI really doesn't need it (since the runc config.json has an option to configure the user)

**Comment by mrunalp** [comment]
We would want to be able to know that as part of CRI to be able to set the user in the config. Can you ask this on the CRI PR upstream?

**Comment by runcom** [comment]
@mrunalp sure

**Comment by runcom** [comment]
@mrunalp asked this at https://github.com/kubernetes/kubernetes/pull/25899/files#r70996068 (the PR is already merged, not sure if you meant another CRI PR which I'm not aware of)

**Comment by mrunalp** [comment]
There is 17048

**Comment by runcom** [comment]
Discussion moved to k8s now, thanks Mrunal
